<?php

return array(
    'jp'   =>	array(
	'num'	     =>  1,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '2010-11-22 00:00:00',
	'endDate'    =>  '2010-11-28 23:59:59',
    ),
    'com'  =>	array(
	'num'	     =>  2,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '2010-11-21 00:00:00',
	'endDate'    =>  '2010-11-24 23:59:59',
    ),
    'net'  =>	array(
	'num'	     =>  3,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'org'  =>	array(
	'num'	     =>  4,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'info'  =>	array(
	'num'	     =>  5,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'biz'  =>	array(
	'num'	     =>  6,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'bz'  =>	array(
	'num'	     =>  7,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'cc'  =>	array(
	'num'	     =>  8,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'cx'  =>	array(
	'num'	     =>  9,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'in'  =>	array(
	'num'	     =>  10,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'la'  =>	array(
	'num'	     =>  11,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'me'  =>	array(
	'num'	     =>  12,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'sc'  =>	array(
	'num'	     =>  13,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'tv'  =>	array(
	'num'	     =>  14,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'tw'  =>	array(
	'num'	     =>  15,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'vc'  =>	array(
	'num'	     =>  16,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'ws'  =>	array(
	'num'	     =>  17,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'asia'  =>	array(
	'num'	     =>  18,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'mobi'  =>	array(
	'num'	     =>  19,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'co.jp'  =>	array(
	'num'	     =>  20,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'ne.jp'  =>	array(
	'num'	     =>  21,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'or.jp'  =>	array(
	'num'	     =>  22,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
    'gr.jp'  =>	array(
	'num'	     =>  23,
	'disabled'   =>  false,
	'checked'    =>  '',
	'startDate'  =>  '',
	'endDate'    =>  '',
    ),
);
